import 'models/categories.dart';

final supply = [
  Perishable(
      name: 'Apples',
      id: '001',
      brand: 'BrandA',
      category: 'food',
      image: "assets/images/apples.png",
      description: dummyText,
      price: 1.5,
      expirationDate: '2022-01-31'
      //expirationDate: DateTime.now().toString(),
      ),
  Perishable(
    name: 'Bananas',
    id: '002',
    brand: 'BrandA',
    category: 'food',
    image: "assets/images/banana.png", description: dummyText,
    price: 1.2,
    expirationDate: '2022-06-14',
    //expirationDate: DateTime.now().toString(),
  ),
  Perishable(
    name: 'Oranges',
    id: '003',
    brand: 'BrandA',
    category: 'food',
    image: "assets/images/orange.png", description: dummyText,
    price: 0.5,
    expirationDate: '2022-06-14',
    //expirationDate: DateTime.now().toString(),
  ),
  Perishable(
      name: 'milk',
      id: '004',
      brand: 'BrandM',
      category: 'beverages',
      image: "assets/images/milk.png",
      description: dummyText,
      price: 0.99,
      expirationDate: '2022-02-02'),
  Clothes(
    name: 'T-shirt',
    brand: 'BrandT',
    id: '005',
    category: 'clothes',
    image: "assets/images/t-shirt.png",
    description: dummyText,
    price: 15.99,
    color: 'violet',
    sizeS: '',
  ),
  Clothes(
    name: 'Hoddie',
    brand: 'BrandT',
    id: '006',
    category: 'clothes',
    image: "assets/images/hoodie.png",
    description: dummyText,
    price: 19.99,
    color: 'violet',
    sizeS: '',
  ),
  Appliance(
      name: 'Laptop',
      category: 'appliance',
      id: '007',
      brand: 'BrandL',
      image: "assets/images/laptop.png",
      price: 2345,
      model: 'ModelL',
      productionDate: '2021-03-03',
      description: dummyText,
      weight: 1.125),
  Appliance(
      name: 'Smart Phone',
      category: 'appliance',
      id: '008',
      brand: 'BrandL',
      image: "assets/images/phone.png",
      description: dummyText,
      price: 890,
      model: 'ModelL',
      productionDate: '2021-03-08',
      weight: 1.125),
  Perishable(
    name: 'Meat',
    id: '009',
    brand: 'BrandA',
    category: 'food', description: dummyText,
    image: "assets/images/raw_meat.png",
    price: 7,
    expirationDate: '2022-06-14',
    //expirationDate: DateTime.now().toString(),
  ),
  Perishable(
      name: 'Beer',
      id: '010',
      brand: 'BrandM',
      description: dummyText,
      category: 'beverages',
      image: "assets/images/beer.png",
      price: 1.99,
      expirationDate: '2023-02-02'),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
